### ISSUE TITLE
Rendering failed with a known bug. Please try a rebuild.

### ISSUE THREAD

**Issue by welbertim** [Madrapps/Pikolo#17] opened 2017-06-14 07:02 UTC
When i use this using theme Appcompat I receveid the message on layout editor "Rendering failed with a known bug. Please try a rebuild.". Please fix this,is a good lib.

**Comment by instrap** [comment] 2017-06-14 15:54
@welbertim Which version of Studio are you using? Also try building the app, I believe this is just an issue in the Layout Editor. The build should work fine. Anyways we will look into why it's not displaying in the Layout editor.

**Comment by thsaravana** [comment] 2017-06-15 01:15
The below is the error message in Layout Editor in` Studio 2.3.2`:
<img width="817" alt="screen shot 2017-06-14 at 9 06 21 pm" src="https://user-images.githubusercontent.com/11502338/27160952-9b18afae-5195-11e7-9890-7c58cca5bacd.png">

The below is the error message in Layout Editor in` Studio 3.0 Preview 3`:
<img width="761" alt="screen shot 2017-06-14 at 9 06 46 pm" src="https://user-images.githubusercontent.com/11502338/27160953-9b1b9ef8-5195-11e7-852d-69bb227bc8fc.png">

`Pikolo` is written completely in Kotlin. I believe the Layout Editor is not able to render Views written in Kotlin. The problem is only with the layout editor. I can still use `HSLColorPicker` in `RelativeLayout` or `ConstraintLayout` and build the app successfully.

**Comment by welbertim** [comment] 2017-06-15 04:32
@instrap  I was using 2.3.2 now I update to 2.3.3.

**Comment by thsaravana** [comment] 2017-06-16 01:03
@welbertim We will keep this issue open until the stable version of Studio 3.0 is released. I believe they will provide support for Kotlin views in Layout Editor. Meanwhile, I will look for some other Kotlin libraries and see if they can render successfully in the Layout editor.

**Comment by thsaravana** [comment] 2019-05-29 01:13
Sorry, I know it's been a long time. Checked in Android Studio 3.4.1 and this issue doesn't occur. The ColorPicker renders properly in the layout editor.

<img width="521" alt="Screenshot 2019-05-25 at 2 13 39 PM" src="https://user-images.githubusercontent.com/11502338/58522245-fb467e00-81dc-11e9-8517-17dae2af6476.png">

**Closed by thsaravana** 2019-05-29 01:13 UTC
Labels: bug
